server:
  port: 8443
  ssl:
    key-store: classpath:pass-man-keystore.p12
    key-store-password: devpasswordman1230
    key-store-type: PKCS12
    key-alias: PasswordManager
    enabled-protocols: TLSv1.3

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pm
      database: pm

app:
  jwt:
    secret: this_is_a_dev_secret_key_with_32+_chars_
    expiryMinutes: 15
  cors:
    origins:
      - http://localhost:5173
      - https://localhost:5173